import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Drawer, NarrowMainHeader } from '@/components';

import { useDrawer } from '@/hooks/useDrawer';

import * as S from './style';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'VoTogether',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { drawerRef, closeDrawer, openDrawer } = useDrawer('left');

  return (
    <html lang='en'>
      <body className={inter.className}>
        <S.HeaderWrapper>
          <NarrowMainHeader handleMenuOpenClick={openDrawer} />
        </S.HeaderWrapper>
        <S.DrawerWrapper>
          <Drawer
            handleDrawerClose={closeDrawer}
            placement='left'
            width='225px'
            ref={drawerRef}
          >
            Drawer 예시
          </Drawer>
        </S.DrawerWrapper>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
