import Header from '@/components/server/Header';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className='max-w-screen-xl mx-auto'>
        <Header />
        {children}
      </body>
    </html>
  );
}
